AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create a Glue database, crawler, and ETL jobs using an existing IAM role.

Resources:
  GlueDatabase:
    Type: 'AWS::Glue::Database'
    Properties: 
      CatalogId: 952084545413
      DatabaseInput: 
        Name: my_database

  CombineDataETLJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: combine_data_job
      Role: arn:aws:iam::952084545413:role/LabRole
      Command:
        Name: glueetl
        ScriptLocation: 's3://bigdata-dataset/scripts/facts_trial_job.py'
        PythonVersion: '3'
      DefaultArguments:
        '--TempDir': 's3://bigdata-dataset/temp/'
        '--job-bookmark-option': 'job-bookmark-enable'
      MaxRetries: 0
      Timeout: 2880
      GlueVersion: '4.0'
      NumberOfWorkers: 2
      WorkerType: G.1X
