name: AWS Resource Creation 
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Deploy_CFT:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload Scripts to S3 Bucket
        run: |
          aws s3 cp Products_Glue_Job.py s3://flipcartdataset/scripts/
          aws s3 cp Sales.py s3://flipcartdataset/scripts/
          
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --stack-name AutomateStack \
            --template-file .github/workflows/CFT.yml \
            --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          continue-on-error: true

      - name: Fetch CloudFormation Failure Events
        if: failure()  # This step runs only if the previous step fails
        run: |
          aws cloudformation describe-stack-events --stack-name AutomateStack | grep "ResourceStatusReason"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

