AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Automated AWS Data Pipeline with Glue, Lambda, and Athena"

Resources:
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties: 
      CatalogId: 952084545413
      DatabaseInput: 
        Name: my_database

  GluedimCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: data-crawler-products 
      Role: arn:aws:iam::952084545413:role/LabRole
      DatabaseName: my_database
      Targets:
        S3Targets:
          - Path: 's3://cftcleandata/product _cleandata/'

  GluefactCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: data-crawler-fact
      Role: arn:aws:iam::952084545413:role/LabRole
      DatabaseName: my_database
      Targets:
        S3Targets:
          - Path: 's3://s3://cftcleandata/sales_cleandata/'

  GlueDimData:
    Type: AWS::Glue::Job
    Properties:
      Name: Product_Glue_Job
      Description: "data-processing-job for product data"
      GlueVersion: 4.0
      MaxRetries: 0
      NumberOfWorkers: 2
      Role: arn:aws:iam::952084545413:role/LabRole
      Timeout: 90
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://bigdata-dataset/scripts/Products_data.py

  GluefactData:
    Type: AWS::Glue::Job
    Properties:
      Name: Product_Glue_Job_Fact  # Changed the name to make it unique
      Description: "data-processing-job for fact data"
      GlueVersion: 4.0
      MaxRetries: 0
      NumberOfWorkers: 2
      Role: arn:aws:iam::952084545413:role/LabRole
      Timeout: 90
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://bigdata-dataset/scripts/Sales_data.py
