AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template"

Resources:
  GlueJobSalesData:
    Type: 'AWS::Glue::Database'
    Properties:
      Name: Sales_Glue_Job
      Description: Ingests data from s3 and after doing transformation it writes the data as a parquet file to the data warehouse
      GlueVersion: 4.0
      MaxRetries: 0
      NumberOfWorkers: 8
      Role: arn:aws:iam::952084545413:role/LabRole
      Timeout: 90
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://flipkart-dataset/scripts/Sales.py
        
  GlueJobProductsData:
    Type: AWS::Glue::Job
    Properties:
      Name: Product_Glue_Job
      Description: Ingests data from RDS and after doing transformation it writes the data as a parquet file to the data warehouse
      GlueVersion: 4.0
      MaxRetries: 0
      NumberOfWorkers: 8
      Role: arn:aws:iam::952084545413:role/LabRole
      Timeout: 90
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://flipkart-dataset/scripts/Products_Glue_Job.py
